apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: mjolnir-archive-service
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: images.paas.redhat.com/thofman/mjolnir-archive-service:latest
    importPolicy:
      scheduled: true
    name: latest
    referencePolicy:
      type: Source
