apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The JGroups ping port for clustering.
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    application: mjolnir-archive-service
    xpaas: "1.1.0"
  name: mjolnir-archive-service-ping
spec:
  clusterIP: None
  ports:
  - name: ping
    port: 8888
    protocol: TCP
    targetPort: 8888
  publishNotReadyAddresses: true
  selector:
    deploymentConfig: mjolnir-archive-service
  sessionAffinity: None
  type: ClusterIP
